[package]
name = "wslattr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5.23", features = ['derive'] }
regex = "^1.1.11"
time = { version = "^0.3.37", features = ['formatting'] }
windows-registry = "^0.3.0"

[dependencies.windows]
version = "^0.58.0"
features = [
    "Wdk_Foundation",
    "Wdk_Storage_FileSystem",
    "Win32_System_Kernel",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_FileSystem",
]
