[package]
name = "wslattr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5.20", features = ['derive'] }
ntapi = { version = "^0.4.1", features = ['impl-default'] }
registry = "^1.2.3"
time = { version = "^0.3.36", features = ['formatting'] }
utfx = "^0.1.0"

[dependencies.winapi]
version = "^0.3.9"
features = [
    "cfg",
    "evntrace",
    "fileapi",
    "in6addr",
    "inaddr",
    "impl-default",
    "ioapiset",
    "minwinbase",
    "ntsecapi",
    "winbase",
    "windef",
    "winerror",
    "winioctl",
]
